<style type="text/css">

body {
     background-attachment: fixed;
     background-image: url("/images/b2.jpg");
     background-repeat: repeat;
}

.theswwrapper {
	display:block;
	margin:0 auto;
	width:80%;
	top:70px;
	position:relative;
	height:725px;
}

.theswtrailerext {
	display:inline-block;
	position:relative;
	top:0px;
	margin-right:20px
}

.theswtrailer {
	position:relative;
	margin:0px auto 0 auto;
	width: 100%;
	float: left;
	background-color:#000000;
	box-shadow: 3px 3px 3px #555555;
	padding-right:0px;

}

.theswlogo {
	position:relative;
	margin:0px auto;
	float:left;
	top:0px;
	padding-right:0px;

}

.theswcopy {
	position:relative;
	top:0px;
	color:#FFFFFF;
	text-align:left;
	left:0px;
	font-size: 13px;
}


.theswbutton {
 	position:relative;
	margin:30px auto 0 auto;
	top:5px;
}


.logocopy {
	position:relative;
	top:0px;
	text-align:left;
	width:450px;
	display:inline-block;
}
</style>

<div class="theswwrapper">
  <div style='margin-left: auto; margin-right: auto; width: 100%;  text-align:center;'>
</div>
<div class="theswtrailerext">
<div class="theswtrailer" style=' border: 1px solid #000; - moz-border-radius:5px; padding-left:border-radius:5px; margin-bottom:50px;'>
<iframe width="450" height="285" src="http://www.youtube.com/embed/ZU_uQUGMmfI?rel=0" frameborder="0" allowfullscreen></iframe></div>
</div>

<div class="logocopy">
<div class="theswlogo"><br><a href='#'><img id="index_01" src="/images/logo.png" width="100%"  alt="Digidev Presents Something Weird" border="0"/></a></div>
<div class="theswcopy">
  <p><br>
    <strong>SOMETHING WEIRD</strong><br><br>Something Weird offers access to an extensive compilation of films from the 1930s through to the 70s that have never before been offered in video formats.
  <br><br>
    Specializing in offbeat genres including the film collections of renowned "King of Sexploitation" David F. Friedman plus titles from the acclaimed "Godfather of Gore" Herschell Gordon Lewis amongst many others, the SWV library is a treasure trove of the unconventional, unusual and interesting that captures the imagination of true film fans from around the globe.  </p>
  <p>&nbsp;</p>
  <p><a href="/index/signin/"><img src="/images/SignIn_.png" width="153" height="79" /></a><br>
    <br><br><br>
  </p>
</div>
</div>


<div class="theswbutton">
        <a href='<?php echo $this->register_page?>'>
          <img id="button" src="/images/2.png" border="0" alt="" />
        </a>
</div>


</div>
