<style type="text/css">

body {
     background-attachment: fixed;
     background-image: url("/images/b2.jpg");
     background-repeat: repeat;
}

.form-container {
   border: 1px solid #680000;
   background: #870000;
   background: -webkit-gradient(linear, left top, left bottom, from(#ff0000), to(#870000));
   background: -webkit-linear-gradient(top, #A10909, #5D0909);
   background: -moz-linear-gradient(top, #A10909, #5D0909);
   background: -ms-linear-gradient(top, #A10909, #5D0909);
   background: -o-linear-gradient(top, #A10909, #5D0909);
   background-image: -ms-linear-gradient(top, #ff0000 0%, #870000 100%);
   -webkit-border-radius: 8px;
   -moz-border-radius: 8px;
   border-radius: 8px;
   -webkit-box-shadow: rgba(000,000,000,0.9) 0 1px 2px, inset rgba(255,255,255,0.4) 0 0px 0;
   -moz-box-shadow: rgba(000,000,000,0.9) 0 1px 2px, inset rgba(255,255,255,0.4) 0 0px 0;
   box-shadow: rgba(000,000,000,0.9) 0 1px 2px, inset rgba(255,255,255,0.4) 0 0px 0;
   font-family: 'Myriad Pro', sans-serif;
   font-size:14px;
   text-decoration: none;
   vertical-align: middle;
   min-width:425px;
   padding:20px;
   width:425px;
   margin-left: auto;
   margin-right: auto
   }
.form-field {
	border: 1px solid #000000;
	background: #ffffff;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
	color: #000000;
	-webkit-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(000,000,000,0.7) 0 0px 0px;
	-moz-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(000,000,000,0.7) 0 0px 0px;
	box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(000,000,000,0.7) 0 0px 0px;
	padding: 8px;
	margin-bottom: 5px;
	width: 280px;
   }
.form-field:focus {
   background: #fff;
   color: #0c93c4;
   }
.form-container h2 {
   text-shadow: #680000 0 1px 0;
   font-size:14px;
   margin: 0 0 10px 0;
   font-weight:bold;
   text-align:center;
    }
.form-title {
	margin-bottom: 1px;
	color: #030303;
	text-shadow: #680000 0 1px 0;
   }
.submit-container {
   margin:8px 0;
   text-align:right;
   }
.submit-button {
   border: 1px solid #2d2e2b;
   background: #fafafa;
   background: -webkit-gradient(linear, left top, left bottom, from(#7a7a7a), to(#fafafa));
   background: -webkit-linear-gradient(top, #7a7a7a, #fafafa);
   background: -moz-linear-gradient(top, #7a7a7a, #fafafa);
   background: -ms-linear-gradient(top, #7a7a7a, #fafafa);
   background: -o-linear-gradient(top, #7a7a7a, #fafafa);
   background-image: -ms-linear-gradient(top, #7a7a7a 0%, #fafafa 100%);
   -webkit-border-radius: 4px;
   -moz-border-radius: 4px;
   border-radius: 4px;
   -webkit-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   -moz-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   text-shadow: #fafafa 0 1px 0;
   color: #030303;
   font-family: 'Myriad Pro', sans-serif;
   padding: 8.5px 18px;
   font-size: 13px;
   text-decoration: none;
   vertical-align: middle;
   }
.submit-button:hover {
   border: 1px solid #155d73;
   text-shadow: #000000 0 1px 0;
   background: #000000;
   background: -webkit-gradient(linear, left top, left bottom, from(#b5b8b1), to(#000000));
   background: -webkit-linear-gradient(top, #b5b8b1, #000000);
   background: -moz-linear-gradient(top, #b5b8b1, #000000);
   background: -ms-linear-gradient(top, #b5b8b1, #000000);
   background: -o-linear-gradient(top, #b5b8b1, #000000);
   background-image: -ms-linear-gradient(top, #b5b8b1 0%, #000000 100%);
   color: #fff;
   }
.submit-button:active {
   text-shadow: #31540c 0 1px 0;
   border: 1px solid #447314;
   background: #3cfa0d;
   background: -webkit-gradient(linear, left top, left bottom, from(#6aa436), to(#000000));
   background: -webkit-linear-gradient(top, #6aa436, #3cfa0d);
   background: -moz-linear-gradient(top, #6aa436, #3cfa0d);
   background: -ms-linear-gradient(top, #6aa436, #3cfa0d);
   background: -o-linear-gradient(top, #6aa436, #3cfa0d);
   background-image: -ms-linear-gradient(top, #6aa436 0%, #3cfa0d 100%);
   color: #fff;
   }
    body,p {
	font-family: 'Myriad Pro', sans-serif;
     font-size:13px;
     color:#FFFFFF;
}
a { 
	color:#bebebe; 
	text-decoration:none;
}
a:hover { text-decoration:underline;}

</style>
<div>
   <div style='height: 130px'></div>
   <div style='margin-left:auto;margin-right:auto;width:100%;text-align:center'>
	<?php echo $this->signin_form?>
<!--
    		<table border='0' style='margin:0 auto;'>

    			<tr>
    				<td><input type='text' style='width: 200px' placeholder='Email'></input></td>
    			</tr>
				<tr>
    				<td>&nbsp;</td>
    			</tr>
    			<tr>
    				<td align='right'><a href='/index/forgetpassword'>Forget Password?</a></td>
    			</tr>
    			<tr>
    				<td><input type='password' style='width: 200px' placeholder='Password'></input></td>
    			</tr>
    			<tr>
    				<td>&nbsp;</td>
    			</tr>
    			<tr>
    				<td><input type='submit' value='Continue'></input></td>
    			</tr>
    		</table>
 -->

   </div>

</div>
